name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  static_code:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

     
      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24.3.4.16"
          elixir-version: "1.16.1"

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ inputs.otp }}-${{ inputs.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install dependencies
        run: mix deps.get

      - name: Run Credo
        run: mix credo --ignore design

      - name: Run Sobelow
        run: mix sobelow

      - name: Audit deps
        run: mix deps.Audit
      
      - name: Audit Hex deps
        run: mix hex.Audit
